//------------------------------------------------------------------------------
// <auto-generated>
//     本文件由 Revolution.ExcelTool 自动生成（容器类），请勿手动修改。
//     重新导表会整体覆盖。生成时间：2026-09-14 22:50:53
// </auto-generated>
//------------------------------------------------------------------------------
namespace Revolution
{
    /// <summary>Hero 表的容器（主键：ID，9 个字段，5 条数据）</summary>
    public sealed class HeroTable : RevDataTable<int, Hero>
    {
        /// <summary>便捷访问；未加载时为 null（先 RevDataTableManager.LoadAsync&lt;HeroTable&gt;()）</summary>
        public static HeroTable Instance => RevDataTableManager.Get<HeroTable>();

        /// <summary>表名 = Hero；数据文件默认取逻辑路径 "Data/Hero"</summary>
        public HeroTable() : base("Hero") { }

        /// <summary>主键取值</summary>
        protected override int GetKey(in Hero data) => data.Id;

        /// <summary>一行文本 → 一条数据（生成代码，零反射、零装箱）</summary>
        protected override bool ParseRow(string[] cells, out Hero data)
        {
            data = default;

            // 列数比结构少 → 数据文件与结构不匹配，按坏行处理
            if (cells.Length < 9) return false;

            data.Id = RevDataFieldParser.ToInt(cells[0]);                 // 英雄ID
            data.Name = RevDataFieldParser.ToStr(cells[1]);               // 英雄名
            data.Quality = RevDataFieldParser.ToInt(cells[2]);            // 品质(1-5)
            data.Attack = RevDataFieldParser.ToFloat(cells[3]);           // 攻击力
            data.Hp = RevDataFieldParser.ToInt(cells[4]);                 // 生命值
            data.MoveSpeed = RevDataFieldParser.ToFloat(cells[5]);        // 移动速度
            data.IsRanged = RevDataFieldParser.ToBool(cells[6]);          // 是否远程
            data.Camp = RevDataFieldParser.ToStr(cells[7]);               // 所属阵营
            data.Desc = RevDataFieldParser.ToStr(cells[8]);               // 英雄描述

            return true;
        }
    }

    /// <summary>Item 表的容器（主键：ID，6 个字段，5 条数据）</summary>
    public sealed class ItemTable : RevDataTable<int, Item>
    {
        /// <summary>便捷访问；未加载时为 null（先 RevDataTableManager.LoadAsync&lt;ItemTable&gt;()）</summary>
        public static ItemTable Instance => RevDataTableManager.Get<ItemTable>();

        /// <summary>表名 = Item；数据文件默认取逻辑路径 "Data/Item"</summary>
        public ItemTable() : base("Item") { }

        /// <summary>主键取值</summary>
        protected override int GetKey(in Item data) => data.Id;

        /// <summary>一行文本 → 一条数据（生成代码，零反射、零装箱）</summary>
        protected override bool ParseRow(string[] cells, out Item data)
        {
            data = default;

            // 列数比结构少 → 数据文件与结构不匹配，按坏行处理
            if (cells.Length < 6) return false;

            data.Id = RevDataFieldParser.ToInt(cells[0]);                 // 物品ID
            data.Name = RevDataFieldParser.ToStr(cells[1]);               // 物品名
            data.Type = RevDataFieldParser.ToInt(cells[2]);               // 类型(1消耗品/2装备)
            data.Price = RevDataFieldParser.ToFloat(cells[3]);            // 售价
            data.Stackable = RevDataFieldParser.ToBool(cells[4]);         // 可否叠加
            data.Desc = RevDataFieldParser.ToStr(cells[5]);               // 物品描述

            return true;
        }
    }

    /// <summary>Skill 表的容器（主键：ID，7 个字段，4 条数据）</summary>
    public sealed class SkillTable : RevDataTable<int, Skill>
    {
        /// <summary>便捷访问；未加载时为 null（先 RevDataTableManager.LoadAsync&lt;SkillTable&gt;()）</summary>
        public static SkillTable Instance => RevDataTableManager.Get<SkillTable>();

        /// <summary>表名 = Skill；数据文件默认取逻辑路径 "Data/Skill"</summary>
        public SkillTable() : base("Skill") { }

        /// <summary>主键取值</summary>
        protected override int GetKey(in Skill data) => data.Id;

        /// <summary>一行文本 → 一条数据（生成代码，零反射、零装箱）</summary>
        protected override bool ParseRow(string[] cells, out Skill data)
        {
            data = default;

            // 列数比结构少 → 数据文件与结构不匹配，按坏行处理
            if (cells.Length < 7) return false;

            data.Id = RevDataFieldParser.ToInt(cells[0]);                 // 技能ID
            data.Name = RevDataFieldParser.ToStr(cells[1]);               // 技能名
            data.HeroID = RevDataFieldParser.ToInt(cells[2]);             // 所属英雄ID
            data.Cooldown = RevDataFieldParser.ToFloat(cells[3]);         // 冷却(秒)
            data.Damage = RevDataFieldParser.ToFloat(cells[4]);           // 伤害
            data.IsUltimate = RevDataFieldParser.ToBool(cells[5]);        // 是否大招
            data.Desc = RevDataFieldParser.ToStr(cells[6]);               // 技能描述

            return true;
        }
    }

    /// <summary>Buff 表的容器（主键：ID，6 个字段，4 条数据）</summary>
    public sealed class BuffTable : RevDataTable<string, Buff>
    {
        /// <summary>便捷访问；未加载时为 null（先 RevDataTableManager.LoadAsync&lt;BuffTable&gt;()）</summary>
        public static BuffTable Instance => RevDataTableManager.Get<BuffTable>();

        /// <summary>表名 = Buff；数据文件默认取逻辑路径 "Data/Buff"</summary>
        public BuffTable() : base("Buff") { }

        /// <summary>主键取值</summary>
        protected override string GetKey(in Buff data) => data.Id;

        /// <summary>一行文本 → 一条数据（生成代码，零反射、零装箱）</summary>
        protected override bool ParseRow(string[] cells, out Buff data)
        {
            data = default;

            // 列数比结构少 → 数据文件与结构不匹配，按坏行处理
            if (cells.Length < 6) return false;

            data.Id = RevDataFieldParser.ToStr(cells[0]);                 // 状态ID(字符串主键)
            data.Name = RevDataFieldParser.ToStr(cells[1]);               // 状态名
            data.Type = RevDataFieldParser.ToInt(cells[2]);               // 类型
            data.Duration = RevDataFieldParser.ToFloat(cells[3]);         // 持续(秒)
            data.Stackable = RevDataFieldParser.ToBool(cells[4]);         // 可否叠加
            data.Desc = RevDataFieldParser.ToStr(cells[5]);               // 状态描述

            return true;
        }
    }
}
