//------------------------------------------------------------------------------
// <auto-generated>
//     本文件由 Revolution.ExcelTool 自动生成（数据结构类），请勿手动修改。
//     重新导表会整体覆盖。生成时间：2026-09-14 22:50:53
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Revolution
{
    /// <summary>Hero —— 配置表的一条数据（对应 Excel 一行；struct：值类型，零 GC）</summary>
    [Serializable]
    public struct Hero
    {
        /// <summary>英雄ID（★ 主键）</summary>
        public int Id;

        /// <summary>英雄名</summary>
        public string Name;

        /// <summary>品质(1-5)</summary>
        public int Quality;

        /// <summary>攻击力</summary>
        public float Attack;

        /// <summary>生命值</summary>
        public int Hp;

        /// <summary>移动速度</summary>
        public float MoveSpeed;

        /// <summary>是否远程</summary>
        public bool IsRanged;

        /// <summary>所属阵营</summary>
        public string Camp;

        /// <summary>英雄描述</summary>
        public string Desc;
    }

    /// <summary>Item —— 配置表的一条数据（对应 Excel 一行；struct：值类型，零 GC）</summary>
    [Serializable]
    public struct Item
    {
        /// <summary>物品ID（★ 主键）</summary>
        public int Id;

        /// <summary>物品名</summary>
        public string Name;

        /// <summary>类型(1消耗品/2装备)</summary>
        public int Type;

        /// <summary>售价</summary>
        public float Price;

        /// <summary>可否叠加</summary>
        public bool Stackable;

        /// <summary>物品描述</summary>
        public string Desc;
    }

    /// <summary>Skill —— 配置表的一条数据（对应 Excel 一行；struct：值类型，零 GC）</summary>
    [Serializable]
    public struct Skill
    {
        /// <summary>技能ID（★ 主键）</summary>
        public int Id;

        /// <summary>技能名</summary>
        public string Name;

        /// <summary>所属英雄ID</summary>
        public int HeroID;

        /// <summary>冷却(秒)</summary>
        public float Cooldown;

        /// <summary>伤害</summary>
        public float Damage;

        /// <summary>是否大招</summary>
        public bool IsUltimate;

        /// <summary>技能描述</summary>
        public string Desc;
    }

    /// <summary>Buff —— 配置表的一条数据（对应 Excel 一行；struct：值类型，零 GC）</summary>
    [Serializable]
    public struct Buff
    {
        /// <summary>状态ID(字符串主键)（★ 主键）</summary>
        public string Id;

        /// <summary>状态名</summary>
        public string Name;

        /// <summary>类型</summary>
        public int Type;

        /// <summary>持续(秒)</summary>
        public float Duration;

        /// <summary>可否叠加</summary>
        public bool Stackable;

        /// <summary>状态描述</summary>
        public string Desc;
    }
}
